version: '3.4'

services: 
    postgres:
        image: postgres:12
        restart: always
        ports:
            - '5432:5432'
        environment: 
            - POSTGRES_PASSWORD=test
            - POSTGRES_USER=test
            - POSTGRES_DB=comisaria
        volumes: 
            - ./test_scripts_db:/docker-entrypoint-initdb.d/
    web:
        build:
            context: ./Backend
            target: development
        image: web:dev
        environment: 
            - PGUSER=test
            - PGHOST=postgres
            - PGPASSWORD=test
            - PGDATABASE=comisaria
            - PGPORT=5432
            - EXPRESSPORT=3000
            - NODE_ICU_DATA=/code/node_modules/full-icu
        ports: 
            - '3000:3000'
        volumes:
            - ./Backend:/code
        depends_on: 
            - postgres
        